apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata: 
 name: my-cluster
spec:
 kafka:
   replicas: 1
   listeners:
     #external:
       #type: route
       #type: loadbalancer
       #tls: false
     plain: {}
     tls: {}
   config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1    
   storage:
     type: ephemeral
 zookeeper:
   replicas: 1
   storage:
     type: ephemeral
 entityOperator:
   topicOperator: {}
   
   #oc adm policy add-cluster-role-to-user cluster-admin developer